"use client";
import Link from "next/link";
import { Bag, Heart, MagnifyingGlass, ArrowRight } from "@phosphor-icons/react";

const pieces=[
  {name:"Aarohi Chandbalis",detail:"Crystal drop earrings",image:"/images/kaushals/reference-collection.jpg"},
  {name:"Ira Signet Ring",detail:"Diamond-set gold ring",image:"/images/kaushals/reference-works.jpg"},
  {name:"Nura Pearl Drops",detail:"Pearl-chain earrings",image:"/images/kaushals/reference-pearl.webp"},
];
export default function KaushalsHome(){return <main className="kh-home"><section className="kh-hero"><header className="kh-nav"><Link href="/" className="kh-logo">KAUSHALS<span>ARTFUL ORNAMENT</span></Link><nav><Link href="/shop">Shop</Link><Link href="/collections">Collections</Link><Link href="/about">Our story</Link></nav><div><Link aria-label="Search" href="/search"><MagnifyingGlass/></Link><Link aria-label="Wishlist" href="/wishlist"><Heart/></Link><Link aria-label="Bag" href="/cart"><Bag/></Link></div></header><svg className="kh-line kh-line-left" viewBox="0 0 520 300" aria-hidden="true"><path d="M-30 220C115 260 70 15 280 75C450 123 295 255 538 138"/></svg><svg className="kh-line kh-line-right" viewBox="0 0 520 300" aria-hidden="true"><path d="M-30 184C120 42 232 274 332 118C400 10 426 114 534 58"/></svg><div className="kh-hero-copy"><p>Kaushals / crafted for the occasion</p><h1>Symbols of <em>celebration.</em></h1><div className="kh-hero-cta"><span>Jewellery that turns a quiet moment into an entrance. Chosen for how it catches the light — and how it makes you feel.</span><Link href="/shop">Explore the edit <ArrowRight/></Link></div></div><img className="kh-model" src="/images/kaushals/hero-model.png" alt="Kaushals model wearing green stone jewellery"/><div className="kh-mini kh-mini-left"><img src="/images/kaushals/reference-collection.jpg" alt="Aarohi Chandbalis"/><span>Aarohi<br/>Chandbalis</span></div><div className="kh-mini kh-mini-right"><img src="/images/kaushals/reference-pearl.webp" alt="Nura Pearl Drops"/><span>Nura<br/>Pearl Drops</span></div></section><section className="kh-discovery"><p className="kh-overline">The Kaushals edit</p><h2>Find your perfect piece.</h2><div className="kh-tabs"><button className="active">Top sellers</button><button>New arrivals</button><button>Rings</button><button>Earrings</button></div><div className="kh-products">{pieces.map((piece,index)=><Link className={`kh-product kh-product-${index}`} href="/shop" key={piece.name}><div className="kh-product-image"><img src={piece.image} alt={piece.name}/></div><small>{piece.detail}</small><h3>{piece.name}</h3><span>Discover piece <ArrowRight/></span></Link>)}</div></section><section className="kh-closing"><p>Personal pieces. Lasting presence.</p><Link href="/collections">Shop Kaushals <ArrowRight/></Link></section></main>}
